[package]
name = "curerr"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/CURVoid/curerr.git"
homepage = "https://github.com/CURVoid/curerr.git"
keywords = ["error", "curerr", "handling"]
description = "Rust crate for easy error handling"